name: Deploy to Windows VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@4
        with:
          dotnet-version: '8.0.410'

      - name: Restore dependencies
        run: dotnet restore ./CodeAssistant/CodeAssistant.sln

      - name: Build
        run: dotnet build ./CodeAssistant/CodeAssistant.sln --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./CodeAssistant/CodeAssistant/CodeAssistant.csproj --configuration Release --output C:\Deploy\WindowsBackend

      - name: Restart Windows Backend Service
        run: Restart-Service CodeAssistant
        shell: powershell